# Generated by Django 4.0.4 on 2022-06-06 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_date_updated'),
        ('event', '0002_event_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='client.client'),
        ),
    ]
