# Generated by Django 4.0.4 on 2022-06-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='client',
        ),
    ]
