# Generated by Django 4.0.4 on 2022-06-05 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_date_updated'),
        ('contract', '0002_alter_contract_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='client.client'),
            preserve_default=False,
        ),
    ]
